# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frames < Formula
  desc "CLI for publishing, browsing, and resolving Nebari Frames"
  homepage "https://github.com/nebari-dev/nebari-frames"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.6/frames_0.1.6_darwin_amd64.tar.gz"
      sha256 "f4852adcc6f936544df34d0d8f20426a48a0ce6ecc4a94a337143c695e02294b"

      define_method(:install) do
        bin.install "frames"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.6/frames_0.1.6_darwin_arm64.tar.gz"
      sha256 "5554b14cd7cfa302d47798aa523a589751901cb1ba8686f9de6c43a2e17e0b7f"

      define_method(:install) do
        bin.install "frames"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.6/frames_0.1.6_linux_amd64.tar.gz"
      sha256 "d4fceeea4c5e7e7ebe4e5678d23793f5a3d0efadb589d89674de0dcf6e0107a5"
      define_method(:install) do
        bin.install "frames"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.6/frames_0.1.6_linux_arm64.tar.gz"
      sha256 "7cc3d1416115d4caebf840ca81f25472c8bac4476adaefc61bf86e9c09457ab7"
      define_method(:install) do
        bin.install "frames"
      end
    end
  end

  test do
    system "#{bin}/frames", "--version"
  end
end
