# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frames < Formula
  desc "CLI for publishing, browsing, and resolving Nebari Frames"
  homepage "https://github.com/nebari-dev/nebari-frames"
  version "0.1.0-alpha.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.0-alpha.5/frames_0.1.0-alpha.5_darwin_amd64.tar.gz"
      sha256 "d925662518d2e21522eb93192e75746367d6f3c99d7a5cc35c358948f5173384"

      define_method(:install) do
        bin.install "frames"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.0-alpha.5/frames_0.1.0-alpha.5_darwin_arm64.tar.gz"
      sha256 "267a319fe4f0edffaff9685b1e9ea009571f8378f71ff77c6d482ea952f6c143"

      define_method(:install) do
        bin.install "frames"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.0-alpha.5/frames_0.1.0-alpha.5_linux_amd64.tar.gz"
      sha256 "e8da9e837cb36bbbccaf841fb45fd973b093aa50109fd102734f5718a9b2b450"
      define_method(:install) do
        bin.install "frames"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nebari-dev/nebari-frames/releases/download/v0.1.0-alpha.5/frames_0.1.0-alpha.5_linux_arm64.tar.gz"
      sha256 "9f6c58560461b3aa099af52a7879e2438020043bb9fa0242c083f4f1ec08ff25"
      define_method(:install) do
        bin.install "frames"
      end
    end
  end

  test do
    system "#{bin}/frames", "--version"
  end
end
