# This file was generated by GoReleaser. DO NOT EDIT.
cask "nic" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "b377f89c124781cae5c4899dc2a3d8541e534505f57eba7ff3c8aebfbdac6a7f"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "431b3bad8bdee96e30b7862b4f1423cbd3a256db96541f254bd1463acbc9a714"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f24fee47e8fc5c21a927180116879a00fe1688e3b213eccd2fb7f332ab98d3b9"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "32aff5463a1ffcba71f03465112e03b274cc362d74ef0894b0057b41674dffcf"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nic"
  desc "Nebari Infrastructure Core - cloud infrastructure management for Nebari"
  homepage "https://github.com/nebari-dev/nebari-infrastructure-core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nic"]
    end
  end

  # No zap stanza required

end
