# This file was generated by GoReleaser. DO NOT EDIT.
cask "nic" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "4b3fdd1574ce691b4e1c4626cf803fdcf890b02ad2c8ee6277e3088dabef3ed0"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d8c58e8c10e85380fc7cdd678923376b596c4f2ff2441a27b5e7385b9ba8f878"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69183ac30e6757f6a3efe73dd9e55db70fa9ad5c6468f70597d61f5fe8a9293c"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "136bdad9485ade977d8a705573750efd031bccc1ce533521eb67276c158fb0bd"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nic"
  desc "Nebari Infrastructure Core - cloud infrastructure management for Nebari"
  homepage "https://github.com/nebari-dev/nebari-infrastructure-core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nic"]
    end
  end

  # No zap stanza required

end
