# This file was generated by GoReleaser. DO NOT EDIT.
cask "nic" do
  version "0.13.0-rc.1"

  on_macos do
    on_intel do
      sha256 "7f5781cc16c13545742a642ddc0b425b87bc85251f79c87512e39b79720508f9"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "79bee11da702d9b2258e650e58699b19f2183627e1a515d465977cace418d057"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68cacdc369c3cdbc64cba31455a6e85f2dd14047a85f65db32eff9b961c691a4"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "266ee976bb57503f9332b4b3f59de718ed7553f33aa59963e09aac0463a83b83"
      url "https://github.com/nebari-dev/nebari-infrastructure-core/releases/download/v#{version}/nebari-infrastructure-core_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nic"
  desc "Nebari Infrastructure Core - cloud infrastructure management for Nebari"
  homepage "https://github.com/nebari-dev/nebari-infrastructure-core"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nic"]
    end
  end

  # No zap stanza required

end
